Adding tests version 1
Dolph111/BankProject pull request #6
Opened 2023-06-27 11:02 UTC by Dolph111

@axelrodvl

2023-06-28 12:15 UTC, axelrodvl commented
Плохое имя коммита. Он должен описывать конкретику, так чтобы после полугода разработки по одному названию коммита было ясно, для чего он.
В данном случае могу прделожить "Deposit repository implementation and tests".
Названия коммитов можно еще у ChatGPT делать, удобно. Закинь код и напиши "озаглавь commit message для этих изменений".

2023-06-28 12:35 UTC, axelrodvl requested changes

2023-06-28 12:35 UTC, axelrodvl commented on src/main/java/Dolphin/demo/controller/DepositController.java
> -        long depositId = depositRepository.createDeposit(deposit);
SRP - Single Responsibility Principle. 
Каждый компонент должен делать строго одну вещь (иное прочтение - работать только на одном уровне абстракции).

По SRP - Controller, отвечающий за REST и/или маппинг запросов и ответов (абстракция - обработка запросов по сети), и сервис, обрабатывающий запрос и готовящий ответ (абстракция - бизнес логика) - это разные сущности.
Для таких вещей выделают сервисы (Service).

Вынеси все содержимое методов createDeposit, approveDeposit и прочее из DepositController в DepositService.

Контроллер должен выглядеть так:
```
@PostMapping("/create")
    public ResponseEntity<String> createDeposit(@RequestBody Deposit deposit) {
         return depositService.createDeposit(deposit);
}
```

Кроме того, возвращать String обычно так себе история.
Заведи в model для каждого запроса соответствующий ответ:
- Deposit/DepositResponse
- ApproveDeposit/ApproveDepositResponse.
- И т.д.
Даже если у тебя ответ - это одна строка, лучше иметь именно объект на запрос, и объект на ответ.

2023-06-28 12:35 UTC, axelrodvl commented on src/main/java/Dolphin/demo/controller/DepositController.java
> +            depositRepository.approveDeposit(deposit);
Названия методов очень важны.
depositRepository.approveDeposit - звучит как команда репозиторию (который хранит данные) выполнить операцию подтверждения депозита (что явно в хранению данных не относится).
Все repository должны иметь CRUD-подобные команды (создать, прочитать, обновить, удалить).
А логика исполнения должна лежать в Service (см. комментарий выше).

2023-06-28 12:35 UTC, axelrodvl commented on src/main/java/Dolphin/demo/controller/DepositController.java
> +    private void sendEmailToBankEmployee(Deposit deposit) {
Совершенно точно не должно быть в DepositController.
Для каждой сущности должны быть свои сервисы.
MailService, DepositService и т.п.
Вынеси метод в MailService (EmailService, как больше нравится).

2023-06-28 12:35 UTC, axelrodvl commented on src/main/java/Dolphin/demo/controller/DepositController.java
> +    private void sendEmailToBankEmployee(Deposit deposit) {
К тому же - твой коммит называется Adding tests - про то, что у тебя сервис научился почту слать, ничего не сказано.
Поэтому это либо должно быть в commit message, либо это два отдельных коммита (лучше два отдельных).

2023-06-28 12:35 UTC, axelrodvl commented on src/test/java/Dolphin/demo/BankProjectApplicationTests.java
> +	void testDeposit() {
Бесполезный тест самого Mockito вместо тестирования твоей логики. Можно убрать.

2023-06-28 12:35 UTC, axelrodvl commented on src/test/java/Dolphin/demo/BankProjectApplicationTests.java
> +		DepositStatus expectedStatus  = DepositStatus.DONE;
Снова бесполезный тест.
Ты говоришь - когда я спрошу doneDeposit, ответь мне DONE. И спрашиваешь.
Ты тестируешь Mockito, а не приложение.

Тест должен проверять результат метода!
Mockito нужен для моков внешний зависимостей.

Например, твой сервис что-то выполняет, и при этом еще и сохраняет данные через repository.
Вот команды к repository можно замокать через Mockito, а вот результат работы сервиса как раз и нужно протестировать без Mockito.

2023-06-28 12:35 UTC, axelrodvl commented on src/main/java/Dolphin/demo/repository/impl/DepositRepositoryImpl.java
> +    public DepositStatus approveDeposit(Deposit deposit){
Это тоже относится к DepositService, а не к Repository.

Repository - хранит данные.
Controller - получает запросы и отправляет ответы.
Service должен выполнять всю логику.

Очень важно - никакой бизнес логики вообще не должно быть ни в Repository, ни в Controller.
Repository может в методе оперировать ID данных в БД, или преобразовывать структуры данных (скажем, разбить строчку на две и в разные места положить), но не должен ничего делать с самим Deposit.

2023-06-28 18:31 UTC, Dolph111 commented
@axelrodvl

2023-07-06 16:27 UTC, axelrodvl commented
Коммит можно переименовать с помощью git commit --ammend

2023-07-30 17:57 UTC, merged